<?php
/*
 * CQPweb: a user-friendly interface to the IMS Corpus Query Processor
 * Copyright (C) 2008-today Andrew Hardie and contributors
 *
 * See http://cwb.sourceforge.net/cqpweb.php
 *
 * This file is part of CQPweb.
 * 
 * CQPweb is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * CQPweb is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


/**
 * @file
 * 
 * Initialises the large array of country codes and names for ISO 3166-1 alpha-2.
 * 
 * Hangs array off the global $Config object, so can be used locally or globally;
 * if locally, declare global $Config first.
 */


/*
 * Note: mostly follows the ISO, but substitutes common names for official UN names
 * wherever this would not lead to ambiguity. 
 * 
 * All "republic of X", "state of X" etc. are omitted for brevity unless they are a
 * critical part of the name, e.g. "Central African Republic", "United States of America".
 * 
 * All alternative names are omitted for brevity.
 * 
 * Plus 00, rather than ZZ, is used for the "unknown" code.
 */
if (!isset($Config->iso31661))
{
	$Config->iso31661 = array (
		'00'=>'--Unknown or not specified--',
		'AD'=>'Andorra',
		'AE'=>'United Arab Emirates',
		'AF'=>'Afghanistan',
		'AG'=>'Antigua and Barbuda',
		'AI'=>'Anguilla',
		'AL'=>'Albania',
		'AM'=>'Armenia',
		'AN'=>'Netherlands Antilles',
		'AO'=>'Angola',
		'AQ'=>'Antarctica',
		'AR'=>'Argentina',
		'AS'=>'American Samoa',
		'AT'=>'Austria',
		'AU'=>'Australia',
		'AW'=>'Aruba',
		'AX'=>'Åland Islands',
		'AZ'=>'Azerbaijan',
		'BA'=>'Bosnia and Herzegovina',
		'BB'=>'Barbados',
		'BD'=>'Bangladesh',
		'BE'=>'Belgium',
		'BF'=>'Burkina Faso',
		'BG'=>'Bulgaria',
		'BH'=>'Bahrain',
		'BI'=>'Burundi',
		'BJ'=>'Benin',
		'BL'=>'Saint Barthélemy',
		'BM'=>'Bermuda',
		'BN'=>'Brunei',
		'BO'=>'Bolivia',
		'BQ'=>'Bonaire, Sint Eustatius and Saba',
		'BR'=>'Brazil',
		'BS'=>'Bahamas',
		'BT'=>'Bhutan',
		'BV'=>'Bouvet Island',
		'BW'=>'Botswana',
		'BY'=>'Belarus',
		'BZ'=>'Belize',
		'IO'=>'British Indian Ocean Territory',
		'CM'=>'Cameroon',
		'CA'=>'Canada',
		'CF'=>'Central African Republic',
		'CC'=>'Cocos (Keeling) Islands',
		'CD'=>'Congo-Kinshasa',
		'CG'=>'Congo-Brazzaville',
		'CI'=>'Côte D’Ivoire',
		'CK'=>'Cook Islands',
		'TD'=>'Chad',
		'CL'=>'Chile',
		'CN'=>'China',
		'CO'=>'Colombia',
		'CR'=>'Costa Rica',
		'CU'=>'Cuba',
		'CV'=>'Cape Verde',
		'CW'=>'Curaçao',
		'CX'=>'Christmas Island',
		'CY'=>'Cyprus',
		'CZ'=>'Czech Republic',
		'DJ'=>'Djibouti',
		'DK'=>'Denmark',
		'DM'=>'Dominica',
		'DO'=>'Dominican Republic',
		'DZ'=>'Algeria',
		'EC'=>'Ecuador',
		'EG'=>'Egypt',
		'SV'=>'El Salvador',
		'GQ'=>'Equatorial Guinea',
		'ER'=>'Eritrea',
		'EE'=>'Estonia',
		'ET'=>'Ethiopia',
		'FI'=>'Finland',
		'FK'=>'Falkland Islands',
		'FO'=>'Faroe Islands',
		'FM'=>'Federated States of Micronesia',
		'FJ'=>'Fiji',
		'FR'=>'France',
		'GF'=>'French Guiana',
		'PF'=>'French Polynesia',
		'TF'=>'French Southern Territories',
		'GA'=>'Gabon',
		'GD'=>'Grenada',
		'GE'=>'Georgia',
		'DE'=>'Germany',
		'GG'=>'Guernsey',
		'GH'=>'Ghana',
		'GI'=>'Gibraltar',
		'GL'=>'Greenland',
		'GM'=>'Gambia',
		'GN'=>'Guinea',
		'GP'=>'Guadeloupe',
		'GR'=>'Greece',
		'GS'=>'South Georgia and the South Sandwich Islands',
		'GT'=>'Guatemala',
		'GU'=>'Guam',
		'GW'=>'Guinea-Bissau',
		'GY'=>'Guyana',
		'HK'=>'Hong Kong',
		'HM'=>'Heard Island and Mcdonald Islands',
		'HN'=>'Honduras',
		'HR'=>'Croatia',
		'HT'=>'Haiti',
		'HU'=>'Hungary',
		'ID'=>'Indonesia',
		'IE'=>'Ireland',
		'IL'=>'Israel',
		'IM'=>'Isle of Man',
		'IN'=>'India',
		'IQ'=>'Iraq',
		'IR'=>'Iran',
		'IS'=>'Iceland',
		'IT'=>'Italy',
		'JE'=>'Jersey',
		'JM'=>'Jamaica',
		'JO'=>'Jordan',
		'JP'=>'Japan',
		'KE'=>'Kenya',
		'KG'=>'Kyrgyzstan',
		'KH'=>'Cambodia',
		'KI'=>'Kiribati',
		'KM'=>'Comoros',
		'KN'=>'Saint Kitts and Nevis',
		'KP'=>'North Korea',
		'KR'=>'South Korea',
		'KW'=>'Kuwait',
		'KY'=>'Cayman Islands',
		'KZ'=>'Kazakhstan',
		'LA'=>'Laos',
		'LB'=>'Lebanon',
		'LC'=>'Saint Lucia',
		'LI'=>'Liechtenstein',
		'LK'=>'Sri Lanka',
		'LR'=>'Liberia',
		'LS'=>'Lesotho',
		'LT'=>'Lithuania',
		'LU'=>'Luxembourg',
		'LV'=>'Latvia',
		'LY'=>'Libya',
		'MA'=>'Morocco',
		'MC'=>'Monaco',
		'MD'=>'Moldova',
		'ME'=>'Montenegro',
		'MF'=>'Saint Martin (French)',
		'MG'=>'Madagascar',
		'MH'=>'Marshall Islands',
		'MK'=>'Macedonia',
		'ML'=>'Mali',
		'MT'=>'Malta',
		'YT'=>'Mayotte',
		'MN'=>'Mongolia',
		'MO'=>'Macao',
		'MQ'=>'Martinique',
		'MR'=>'Mauritania',
		'MS'=>'Montserrat',
		'MU'=>'Mauritius',
		'MV'=>'Maldives',
		'MW'=>'Malawi',
		'MY'=>'Malaysia',
		'MX'=>'Mexico',
		'MZ'=>'Mozambique',
		'MM'=>'Myanmar',
		'NA'=>'Namibia',
		'NR'=>'Nauru',
		'NL'=>'Netherlands',
		'NZ'=>'New Zealand',
		'NC'=>'New Caledonia',
		'NE'=>'Niger',
		'NG'=>'Nigeria',
		'NI'=>'Nicaragua',
		'NU'=>'Niue',
		'NF'=>'Norfolk Island',
		'MP'=>'Northern Mariana Islands',
		'NO'=>'Norway',
		'NP'=>'Nepal',
		'OM'=>'Oman',
		'PA'=>'Panama',
		'PE'=>'Peru',
		'PG'=>'Papua New Guinea',
		'PH'=>'Philippines',
		'PK'=>'Pakistan',
		'PS'=>'Palestine',
		'PL'=>'Poland',
		'PN'=>'Pitcairn',
		'PR'=>'Puerto Rico',
		'PT'=>'Portugal',
		'PW'=>'Palau',
		'PY'=>'Paraguay',
		'QA'=>'Qatar',
		'RE'=>'Réunion',
		'RO'=>'Romania',
		'RS'=>'Serbia',
		'RU'=>'Russia',
		'RW'=>'Rwanda',
		'SH'=>'Saint Helena, Ascension and Tristan da Cunha',
		'PM'=>'Saint Pierre and Miquelon',
		'VC'=>'Saint Vincent and the Grenadines',
		'WS'=>'Samoa',
		'SM'=>'San Marino',
		'ST'=>'São Tomé and Príncipe',
		'SA'=>'Saudi Arabia',
		'SN'=>'Senegal',
		'SC'=>'Seychelles',
		'SL'=>'Sierra Leone',
		'SG'=>'Singapore',
		'SX'=>'Sint Maarten (Dutch)',
		'SK'=>'Slovakia',
		'SI'=>'Slovenia',
		'SB'=>'Solomon Islands',
		'SO'=>'Somalia',
		'ZA'=>'South Africa',
		'SS'=>'South Sudan',
		'ES'=>'Spain',
		'SD'=>'Sudan',
		'SR'=>'Suriname',
		'SZ'=>'Swaziland',
		'SE'=>'Sweden',
		'CH'=>'Switzerland',
		'SJ'=>'Svalbard and Jan Mayen',
		'SY'=>'Syria',
		'TC'=>'Turks and Caicos Islands',
		'TG'=>'Togo',
		'TH'=>'Thailand',
		'TJ'=>'Tajikistan',
		'TK'=>'Tokelau',
		'TL'=>'Timor-Leste',
		'TM'=>'Turkmenistan',
		'TN'=>'Tunisia',
		'TO'=>'Tonga',
		'TR'=>'Turkey',
		'TT'=>'Trinidad and Tobago',
		'TV'=>'Tuvalu',
		'TW'=>'Taiwan',
		'TZ'=>'Tanzania',
		'UA'=>'Ukraine',
		'UG'=>'Uganda',
		'GB'=>'United Kingdom',
		'UM'=>'United States Minor Outlying Islands',
		'US'=>'United States of America',
		'UY'=>'Uruguay',
		'UZ'=>'Uzbekistan',
		'VA'=>'Vatican City',
		'VE'=>'Venezuela',
		'VG'=>'Virgin Islands, British',
		'VI'=>'Virgin Islands, U.S.',
		'VN'=>'Vietnam',
		'VU'=>'Vanuatu',
		'WF'=>'Wallis and Futuna',
		'EH'=>'Western Sahara',
		'YE'=>'Yemen',
		'ZM'=>'Zambia',
		'ZW'=>'Zimbabwe'
	);
	asort($Config->iso31661, SORT_NATURAL | SORT_FLAG_CASE);
	//TODO, resort the aactual list above, insteadof sorting at runtime. 
	//the asort puts Aland islands at the end, which is counterintuitive.
}
