version: "3.0"
services:
  cwb:
    image: cwb
    build:
      context: .
    ports:
      - 80:80
    command: ./run-cqp.sh
    stdin_open: true
    tty: true
    volumes:
      - ./corpora:/corpora
      - ./registry:/usr/local/cwb-3.4.15/share/cwb/registry/
      - ./cqp:/cqp
