version: "3.0"
services:
  cwb:
    image: cwb
    build:
      context: .
    ports:
      - 80:80
    command: ./run-cqp.sh
    volumes:
      - ./CQPweb:/var/www
      - ./corpora:/corpora
      - ./registry:/usr/local/share/cwb/registry
      - ./cqp:/cqp
